# Generated by Django 5.1.2 on 2024-10-25 12:09

import yogalevels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YogaLevel",
            fields=[
                (
                    "id",
                    models.SmallAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        db_column="image_file_path",
                        max_length=50,
                        upload_to=yogalevels.models.yoga_level_image_folder,
                    ),
                ),
                ("minimum_points", models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                "db_table": "yoga_level",
                "ordering": ["minimum_points"],
            },
        ),
    ]
