# Generated by Django 5.1.2 on 2024-10-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("yogahistories", "0001_initial"),
        ("yogaposes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yogauser",
            name="yoga_poses",
            field=models.ManyToManyField(
                through="yogahistories.YogaHistory", to="yogaposes.yogapose"
            ),
        ),
    ]
