databases:
  - name: yogayu
    plan: free
    databaseName: yogayu
    user: yogayu

services:
  - type: web
    plan: free
    name: yogayu
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn yogayurest.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yogayu
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4