# Generated by Django 5.1.2 on 2024-10-25 12:09

import django.db.models.deletion
import yogaposes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("yogalevels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YogaPose",
            fields=[
                (
                    "id",
                    models.SmallAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        db_column="image_file_path",
                        max_length=70,
                        upload_to=yogaposes.models.yoga_pose_image_folder,
                    ),
                ),
                ("first_reward_points", models.PositiveSmallIntegerField()),
                (
                    "yoga_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="yogalevels.yogalevel",
                    ),
                ),
            ],
            options={
                "db_table": "yoga_pose",
            },
        ),
    ]
