# Generated by Django 5.1.2 on 2024-10-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("yogaposes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YogaHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_points", models.PositiveSmallIntegerField()),
                ("completed_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.yogauser"
                    ),
                ),
                (
                    "yoga_pose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="yogaposes.yogapose",
                    ),
                ),
            ],
            options={
                "db_table": "yoga_history",
            },
        ),
    ]
