# Generated by Django 4.2.2 on 2023-06-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("yogaposes", "0001_initial"),
        ("users", "0002_yogauser"),
    ]

    operations = [
        migrations.CreateModel(
            name="YogaHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_points", models.PositiveSmallIntegerField()),
                ("completed_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.yogauser"
                    ),
                ),
                (
                    "yoga_pose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="yogaposes.yogapose",
                    ),
                ),
            ],
            options={
                "db_table": "yoga_history",
            },
        ),
    ]
